In [2]:
import numpy as np
import imageio
from PIL import Image,ImageChops

image = imageio.imread('D:\\3rd Semester\\E (AIE203) = DSA-2\\Lab\\Puppy.jpg', as_gray=True)

thresholdValue = np.mean(image)
xDim, yDim = image.shape
norm_Array=np.zeros((xDim,yDim))
inv_Array=np.full((xDim,yDim),255)


for i in range(xDim):
    for j in range(yDim):
        if (image[i][j] > thresholdValue):
            image[i][j] = 1
            norm_Array[i][j]=255
            inv_Array[i][j]=0
        else:
            image[i][j] = 0
print(image)

pil_image=Image.fromarray(image)
pil_Normalimage=Image.fromarray(norm_Array)
pil_Invertedimage=Image.fromarray(inv_Array)

pil_Normalimage.show()
pil_Invertedimage.show()
#pil_Invertedimage = imageio.imwrite('D:\\College\\AIE\\3rdsem\\DSA\\inverted.jpg', as_gray=True)
img1 = Image.open('D:\\3rd Semester\\E (AIE203) = DSA-2\\Lab\\Puppy_Black.jpg')
img2 = Image.open('D:\\3rd Semester\\E (AIE203) = DSA-2\\Lab\\Puppy_Inverted.jpg')

diff = ImageChops.difference(img1,img2)
diff.show()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]
