In [9]:
import numpy as np

class Graph(object):
    def __init__(self, graph=None):
        if graph == None:
            graph = {}
        self.__graph = graph

    def addNode(self, node):
        if node not in self.__graph:
            self.__graph[node] = []

    def addEdge(self, edge):
        edge = set(edge)
        (node1, node2) = tuple(edge)
        if node1 in self.__graph:
            self.__graph[node1].append(node2)
        else:
            self.__graph[node1] = [node2]

    def Nodes(self):
        return list(self.__graph.keys())

    def Edges(self):
        edges = []
        for node in self.__graph:
            for neighbour in self.__graph[node]:
                if (neighbour, node) not in edges:
                    edges.append((node, neighbour))
        return edges

    def __str__(self):
        res = "Nodes: "
        for node in self.Nodes():
            res += str(node) + " "
        res += " Edges: "
        for edge in self.Edges():
            res += str(edge) + " "
        return res

    def neighboursOut(node, outgoing=[]):
        for i in range(len(g.edges())):
            if (g.edges()[i][0]) == node:
                outgoing.append(g.edges()[i][1])
        return outgoing

    def neighboursIn(self, node, incoming=[]):
        for i in range(len(g.edges())):
            if (g.edges()[i][1]) == node:
                incoming.append(g.edges()[i][0])
        return incoming

    def findPath(self, start_node, end_node, path=None):
        if path == None:
            path = []
        graph = self.__graph
        path = path + [start_node]
        if start_node == end_node:
            return path
        if start_node not in graph:
            return None
        for node in graph[start_node]:
            if node not in path:
                extendedPath = self.findPath(node, end_node, path)
                if extendedPath:
                    return extendedPath
        return None

    def iscyclic(self,):
        for i in self.__graph.keys():
            for j in self.__graph.keys():
                for k in self.__graph[j]:
                    if k==i:
                        return True
        return False
            
                    

    def adjmatrix(self):
        print("Adjacency matrix:")
        letters = {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, 'J': 9, 'K': 10, 'L': 11,
                   'M': 12, 'N': 13, 'O': 14, 'P': 15, 'Q': 16, 'R': 17, 'S': 18, 'T': 19, 'U': 20, 'V': 21, 'W': 22,
                   'X': 23, 'Y': 24, 'Z': 25}
        matrix = np.zeros((len(self.__graph), len(self.__graph))).astype(int)
        for i in self.__graph:
            for j in self.__graph[i]:
                matrix[letters[i]][letters[j]] = 1
        print(matrix)


In [10]:
graph1 = {'A': ['B','E'],
         'B': ['A','C','D','E'],
         'C': ['B','D'],
         'D': ['B', 'C','E'],
         'E': ['A','B','D']}
graph2 = {'A': ['C'],
         'B': ['A','C'],
         'C': ['D','B'],
         'D': [],
         'E': []
         }

In [11]:
# printing adjacency matrix
g1 = Graph(graph1)
g1.adjmatrix()

Adjacency matrix:
[[0 1 0 0 1]
 [1 0 1 1 1]
 [0 1 0 1 0]
 [0 1 1 0 1]
 [1 1 0 1 0]]


In [12]:
# printing adjacency list
print("Adjacency list: ")
for i in graph1:
    print(i,end="-->")
    for j in graph1[i]:
        print(j,end=",")
    print()
print()
print("Nodes: ",end="")
print(g1.Nodes())
print("Edges: ",end="")
print(g1.Edges())

Adjacency list: 
A-->B,E,
B-->A,C,D,E,
C-->B,D,
D-->B,C,E,
E-->A,B,D,

Nodes: ['A', 'B', 'C', 'D', 'E']
Edges: [('A', 'B'), ('A', 'E'), ('B', 'C'), ('B', 'D'), ('B', 'E'), ('C', 'D'), ('D', 'E')]


In [13]:
# printing path
print("Path between A and E")
path=g1.findPath("A", "E")
if path != None:
    for x in range(len(path)-1):
        print(path[x]+"->",end="")
    print(path[-1])
else:
    print("None")
    
if g1.iscyclic():
    print("graph is cyclic")
else:
    print("graph is not cyclic")

Path between A and E
A->B->C->D->E
graph is cyclic


In [14]:
# printing adjacency matrix
g2 = Graph(graph2)
g2.adjmatrix()

Adjacency matrix:
[[0 0 1 0 0]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [15]:
# printing adjacency list
print("  Adjacency list:")
for i in graph2:
    print(i,end="-->")
    for j in graph2[i]:
        print(j,end=",")
    print()
print()
print("Nodes: ",end="")
print(g2.Nodes())
print("Edges: ",end="")
print(g2.Edges())

  Adjacency list:
A-->C,
B-->A,C,
C-->D,B,
D-->
E-->

Nodes: ['A', 'B', 'C', 'D', 'E']
Edges: [('A', 'C'), ('B', 'A'), ('B', 'C'), ('C', 'D')]


In [16]:
# printing path
print("Path between C and E")
path=g2.findPath("C", "E")
if path != None:
    for x in range(len(path)-1):
        print(path[x]+"->",end="")
    print(path[-1])
else:
    print("None")

Path between C and E
None
